file = file_text_open_write("gamepad.cfg");
file_text_write_string(file, string(global.joyJumpVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyAttackVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyItemVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyRunVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyBombVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyRopeVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyFlareVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyPayVal));
file_text_writeln(file);
file_text_write_string(file, string(global.joyStartVal));
file_text_close(file);
